plugins {
    id("groovy")
    id("io.micronaut.library") version "4.6.1"
    id("io.micronaut.aot") version "4.4.5"
    id("maven-publish")
    id("com.gradleup.shadow") version "8.3.6"
}

group = 'org.maurodata.plugins'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenLocal()
    maven { url "https://mauro-repository.com/libs-snapshot-local" }
    maven { url "https://mauro-repository.com/libs-release-local" }

    // For DaisyDiff
    maven {url "https://packages.atlassian.com/mvn/maven-atlassian-external"}
    // For org.cyberneko:html
    maven {url "https://repository.ow2.org/nexus/content/repositories/public/"}

    mavenCentral()

    // For snapshot versions of mauro-domain
    // maven {url "https://mauro-repository.com/libs-snapshot-local"}
}


configurations {
    // Define a custom configuration for your platform API
    platformapi

    // Make compileOnly and testImplementation extend from it
    compileOnly.extendsFrom(platformapi)
    testImplementation.extendsFrom(platformapi)
}

dependencies {
    // Not to include in the jar
    compileOnly("io.micronaut.groovy:micronaut-runtime-groovy")
    compileOnly("io.micronaut:micronaut-jackson-databind")
    compileOnly("io.micronaut.security:micronaut-security-annotations")
    compileOnly("io.micronaut.security:micronaut-security-session")
    compileOnly("io.micronaut:micronaut-inject-groovy")
    compileOnly("io.micronaut.data:micronaut-data-processor")
    compileOnly("io.micronaut.data:micronaut-data-jdbc")
    // runtimeOnly("org.yaml:snakeyaml")
    compileOnly ('org.apache.groovy:groovy-json:4.0.19')
    compileOnly group: 'org.apache.groovy', name: 'groovy-xml', version: '4.0.25'
    compileOnly("io.micronaut:micronaut-http-client")
    compileOnly("io.micronaut:micronaut-http-server")
    compileOnly("io.micronaut.cache:micronaut-cache-core")

    compileOnly('org.maurodata:mauro-domain:0.0.3-SNAPSHOT')
    compileOnly('org.maurodata:mauro-persistence:0.0.3-SNAPSHOT')
    compileOnly('org.maurodata:mauro-client:0.0.3-SNAPSHOT')
    compileOnly('org.maurodata:mauro-api:0.0.3-SNAPSHOT')

    compileOnly("io.micronaut.sql:micronaut-jdbc-hikari")
    compileOnly('com.fasterxml.uuid:java-uuid-generator:5.1.0')

    // To include in the jar
    implementation('commons-io:commons-io:2.20.0')
    implementation('org.apache.commons:commons-lang3:3.18.0')

    implementation("org.maurodata:dita-dsl-base:2.0.0-SNAPSHOT")

    implementation("org.maurodata:iso11179-domain:2.0.0-SNAPSHOT") {
        exclude group: "com.sun.xml.bind", module: "jaxb-impl"
    }

    // Daisy Diff and transitive dependencies.  Used in the generation of change requests
    implementation 'ch.sbb.html5diff:html5diff:1.4.5'

    //implementation group: 'org.outerj.daisy', name: 'daisydiff', version: '1.3.3-atlassian-hosted'
    // Source: https://mvnrepository.com/artifact/org.eclipse.compare.core/source
    implementation 'org.eclipse.platform:org.eclipse.compare.core:3.8.800'


    implementation 'net.sourceforge.nekohtml:nekohtml:1.9.22'
    implementation 'xerces:xercesImpl:2.12.2'
    implementation "xml-apis:xml-apis:1.4.01"
    implementation "net.sf.jtidy:jtidy:r938"

    // Required for Daisy Diff (NPE when using Saxon)
    implementation group: 'xalan', name: 'xalan', version: '2.7.3'
    implementation group: 'xalan', name: 'serializer', version: '2.7.3'

    // for build / assemble
    compileOnly("io.micronaut:micronaut-core-reactive")
    aotPlugins("io.micronaut:micronaut-core-reactive")

    // Testing
    //testImplementation("io.micronaut:micronaut-jdbc-hikari")
    testRuntimeOnly("org.postgresql:postgresql")
    testRuntimeOnly("org.flywaydb:flyway-database-postgresql")
    testImplementation("io.micronaut.test:micronaut-test-spock")
    testImplementation("io.micronaut.sql:micronaut-jdbc-hikari:2.2.6")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.2.0")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.2.0")

    testRuntimeOnly("org.testcontainers:testcontainers:2.0.3")
    testRuntimeOnly("org.testcontainers:postgresql:1.21.4")
    testImplementation("io.micronaut:micronaut-http-server-netty")
    testRuntimeOnly("org.postgresql:postgresql")

    testImplementation("junit:junit:4.13.2")
    testImplementation("io.micronaut.test:micronaut-test-junit5")
    testImplementation("org.junit.jupiter:junit-jupiter-api")

    // all of the compileOnly (above) added to test

    testImplementation("io.micronaut.groovy:micronaut-runtime-groovy")
    testImplementation("io.micronaut:micronaut-jackson-databind")
    testImplementation("io.micronaut.security:micronaut-security-annotations")
    testImplementation("io.micronaut.security:micronaut-security-session")
    testImplementation("io.micronaut:micronaut-inject-groovy")
    testImplementation("io.micronaut.data:micronaut-data-processor")
    testImplementation("io.micronaut.data:micronaut-data-jdbc")

    testImplementation ('org.apache.groovy:groovy-json:4.0.19')
    testImplementation group: 'org.apache.groovy', name: 'groovy-xml', version: '4.0.25'

    testImplementation("io.micronaut:micronaut-http-client")
    testImplementation("io.micronaut:micronaut-http-server")
    testImplementation("io.micronaut.cache:micronaut-cache-core")

    testImplementation('org.maurodata:mauro-domain:0.0.3-SNAPSHOT')
    testImplementation('org.maurodata:mauro-persistence:0.0.3-SNAPSHOT')
    testImplementation('org.maurodata:mauro-client:0.0.3-SNAPSHOT')
    testImplementation('org.maurodata:mauro-api:0.0.3-SNAPSHOT')
    testImplementation('com.fasterxml.uuid:java-uuid-generator:5.1.0')

    testImplementation("io.micronaut.sql:micronaut-jdbc-hikari")
}


micronaut {
    runtime("netty")
    testRuntime("spock2")
    processing {
        incremental(true)
        annotations("org.maurodata.*")
    }
}

shadowJar {
    dependencies {
        exclude(dependency("org.apache.groovy:groovy-xml"))
    }
}

java {
    sourceCompatibility = JavaVersion.toVersion("17")
    targetCompatibility = JavaVersion.toVersion("17")
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            name = "MauroSnapshotRepository"
            url = "https://mauro-repository.com/libs-snapshot-local"
            credentials(PasswordCredentials)
            authentication {
                basic(BasicAuthentication)
            }
        }
    }
}

test {
    useJUnitPlatform()
    minHeapSize = "1g" // initial heap size
    maxHeapSize = "20g" // maximum heap size
    //jvmArgs '-XX:MaxPermSize=256m' // mem argument for the test JVM
    dependsOn(':jar')
}